INSERT INTO Region (id_region, nombre_region)
VALUES (1, 'Tarapacá'),
       (2, 'Antofagasta'),
       (3, 'Atacama'),
       (4, 'Coquimbo'),
       (5, 'Valparaíso'),
       (6, 'Región del Libertador Gral. Bernardo O’Higgins'),
       (7, 'Región del Maule'),
       (8, 'Región del Biobío'),
       (9, 'Región de la Araucania'),
       (10, 'Región de Los Lagos'),
       (11, 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
       (12, 'Región de Magallanes y de la Antártica Chilena'),
       (13, 'Región Metropolitana de Santiago'),
       (14, 'Región de Los Ríos'),
       (15, 'Arica y Parinacota'),
       (16, 'Región de Ñuble');